import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually curated sidebar for Cudo Compute SDK documentation
  tutorialSidebar: [
    'index', // Homepage/Overview
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'installation',
        'usage',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'api-reference',
        'architecture',
        {
          type: 'category',
          label: 'API Documentation',
          link: {
            type: 'generated-index',
            title: 'Auto-Generated API Docs',
            description: 'Detailed API documentation generated from SDK source code',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Support',
      items: [
        'troubleshooting',
        'contact',
        'contributing',
      ],
    },
  ],
};

export default sidebars;
